server:
  port: 8888

spring:
  application:
    name: spring-test-config-server
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vivekchulani/spring-cloud-config-properties.git
          skipSslValidation: true
          username:
          password:
    bus:
      enabled: true
  kafka:
    bootstrap-servers: http://localhost:9092
